name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -alias e888key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore e888-release.keystore \
            -storepass 123456 \
            -keypass 123456 \
            -dname "CN=E888, OU=Mobile, O=E888, L=SP, S=SP, C=BR"

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: e888-keystore
          path: e888-release.keystore
